arr = input()
arr = arr.replace("c=",'1')
arr = arr.replace("c-",'1')
arr = arr.replace("dz=",'1')
arr = arr.replace("d-",'1')
arr = arr.replace("lj",'1')
arr = arr.replace("nj",'1')
arr = arr.replace("s=",'1')
arr = arr.replace("z=",'1')
print(len(arr))