while True:
    try:
        arr = input()
        arr = arr.replace('1', '`')
        arr = arr.replace('2', '1')
        arr = arr.replace('3', '2')
        arr = arr.replace('4', '3')
        arr = arr.replace('5', '4')
        arr = arr.replace('6', '5')
        arr = arr.replace('7', '6')
        arr = arr.replace('8', '7')
        arr = arr.replace('9', '8')
        arr = arr.replace('0', '9')
        arr = arr.replace('-', '0')
        arr = arr.replace('=', '-')
        arr = arr.replace('W', 'Q')
        arr = arr.replace('S', 'A')
        arr = arr.replace('X', 'Z')
        arr = arr.replace('E', 'W')
        arr = arr.replace('D', 'S')
        arr = arr.replace('C', 'X')
        arr = arr.replace('R', 'E')
        arr = arr.replace('F', 'D')
        arr = arr.replace('V', 'C')
        arr = arr.replace('T', 'R')
        arr = arr.replace('G', 'F')
        arr = arr.replace('B', 'V')
        arr = arr.replace('Y', 'T')
        arr = arr.replace('H', 'G')
        arr = arr.replace('N', 'B')
        arr = arr.replace('U', 'Y')
        arr = arr.replace('J', 'H')
        arr = arr.replace('M', 'N')
        arr = arr.replace('I', 'U')
        arr = arr.replace('K', 'J')
        arr = arr.replace(',', 'M')
        arr = arr.replace('O', 'I')
        arr = arr.replace('L', 'K')
        arr = arr.replace('.', ',')
        arr = arr.replace('P', 'O')
        arr = arr.replace(';', 'L')
        arr = arr.replace('/', '.')
        arr = arr.replace('[', 'P')
        arr = arr.replace("'", ';')
        arr = arr.replace(']', '[')
        arr = arr.replace('\\', ']')
        print(arr)

    except:
        break